# Generated by Django 4.1.6 on 2023-04-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='history_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание истории'),
        ),
        migrations.AlterField(
            model_name='page',
            name='main_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Главное описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на страницу описания'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='direct_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='support',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Сообщение'),
        ),
    ]
