# Generated by Django 4.1.6 on 2023-04-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_feedback_message_alter_page_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='history_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание истории'),
        ),
        migrations.AlterField(
            model_name='page',
            name='main_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Главное описание'),
        ),
    ]
