# Generated by Django 4.1.6 on 2023-04-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_alter_page_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Полное описание'),
        ),
    ]
