# Generated by Django 4.1.6 on 2023-04-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_alter_feedback_message_alter_page_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='service_list',
            field=models.ManyToManyField(blank=True, to='salon.service', verbose_name='Услуги'),
        ),
    ]
