# Generated by Django 4.1.6 on 2023-04-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_service_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_list',
            field=models.ManyToManyField(blank=True, to='salon.image', verbose_name='Галерея'),
        ),
    ]
