# Generated by Django 4.1.6 on 2023-03-16 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=150)),
                ('deadline', models.IntegerField()),
                ('stage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.stage')),
            ],
        ),
    ]
