# Generated by Django 4.1.6 on 2023-04-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_crmservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиент',
            },
        ),
        migrations.CreateModel(
            name='CRMMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудник',
            },
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Категории услуг', 'verbose_name_plural': 'Категория услуги'},
        ),
        migrations.CreateModel(
            name='CRMSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_session', models.TimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.crmcustomer')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.crmmaster')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.crmservice')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Категория услуги',
            },
        ),
    ]
