# Generated by Django 4.1.6 on 2023-04-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_crmcustomer_crmmaster_alter_stage_options_crmsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmcustomer',
            name='salary',
        ),
        migrations.AlterField(
            model_name='crmcustomer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='crmcustomer',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='crmcustomer',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='crmcustomer',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
