# Generated by Django 4.1.6 on 2023-04-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_crmmaster_name_alter_crmmaster_patronymic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmsession',
            options={'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.AlterField(
            model_name='crmsession',
            name='date_session',
            field=models.DateTimeField(),
        ),
    ]
