# Generated by Django 4.1.6 on 2023-04-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images_tatu', to='tatu.image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_list',
            field=models.ManyToManyField(blank=True, related_name='services_tatu', to='tatu.serviceprice'),
        ),
    ]
