# Generated by Django 4.1.6 on 2023-04-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tatu', '0002_alter_service_images_alter_service_price_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ServiceTatu',
        ),
    ]
