# Generated by Django 4.1.6 on 2023-02-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='test_password',
            field=models.CharField(default='w0d2gv', max_length=60),
        ),
    ]
