# Generated by Django 4.1.6 on 2023-02-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_defaultuser_test_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='password',
            field=models.CharField(default='7e1ijs', max_length=60),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='test_password',
            field=models.CharField(default='aam6au', max_length=60),
        ),
    ]
