# Generated by Django 4.1.6 on 2023-02-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_defaultuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='password',
            field=models.CharField(default='9g3vzn', max_length=60),
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='test_password',
            field=models.CharField(default='9i8ntq', max_length=60),
        ),
    ]
