# Generated by Django 4.1.6 on 2023-02-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_defaultuser_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultuser',
            name='test_password',
        ),
        migrations.AlterField(
            model_name='defaultuser',
            name='password',
            field=models.CharField(default='9nm756', max_length=60),
        ),
    ]
