# Generated by Django 4.1.6 on 2023-02-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_defaultuser_test_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
