# Generated by Django 4.1.6 on 2023-04-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('recipient', models.EmailField(max_length=100, verbose_name='Отправитель')),
                ('description', models.CharField(max_length=500, verbose_name='Сообщение')),
            ],
        ),
    ]
